<?php

namespace AppBundle\Repository;

/**
 * UpdateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpdateRepository extends \Doctrine\ORM\EntityRepository
{
}
