<?php

namespace AppBundle\Repository;

/**
 * UpdateAtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpdateAtRepository extends \Doctrine\ORM\EntityRepository
{
}
